### ISSUE TITLE
Cannot find module 'connect/middleware/router'

### ISSUE THREAD

**Issue by magg** [LockerProject/Locker#3] opened 2011-03-19 04:56 UTC
i can't seem to get locker running i keep getting this error

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
Error: Cannot find module 'connect/middleware/router'
    at Function._resolveFilename (module.js:320:11)
    at Function._load (module.js:266:25)
    at require (module.js:348:19)
    at Object.<anonymous> (/usr/local/lib/node/.npm/express/1.0.0/package/lib/express/server.js:17:14)
    at Module._compile (module.js:404:26)
    at Object..js (module.js:410:10)
    at Module.load (module.js:336:31)
    at Function._load (module.js:297:12)
    at require (module.js:348:19)
    at Object.<anonymous> (/usr/local/lib/node/.npm/express/1.0.0/package/lib/express/index.js:28:31)

I'm using Ubuntu 10.10

Please help!

**Comment by smurthas** [comment] 2011-03-19 15:35
It sounds like you don't have the connect module properly installed. Can you paste the results of <code>npm ls installed</code> here?

**Comment by seancron** [comment] 2011-03-19 20:35
I get this same issue too. Here's the results of `npm ls installed`: http://pastebin.com/uY4Bttab

**Comment by seancron** [comment] 2011-03-19 20:50
Apparently the problem is incompatible versions of connect and express. I solved it by using node 0.4.1, express@1.0.7, and connect@0.5.7

**Comment by temas** [comment] 2011-03-19 20:53
Did you do a npm install in the main directory?  It's looking for the connect package that should have been pulled down as a dependency of the express package.

--temas

**Comment by seancron** [comment] 2011-03-19 21:03
Yeah I did an npm install in the main directory. Completely clean version of node and npm as well (used nvm to install node 0.4.0). I think the problem is not all the dependencies are compatible with each other.

Edit: Just tested under node 0.4.0 again. If express@1.0.7 and connect@0.5.7 it works.

**Comment by magg** [comment] 2011-03-20 05:30
Here's the output of "npm ls installed" and btw I'm using node 0.4.4-pre from the ubuntu ppa

http://pastebin.com/qqcmjTkf

So I need express@1.0.7 and connect@0.5.7 to make it work?? I will try it now, thanks!

**Comment by magg** [comment] 2011-03-20 05:49
mmm I can't uninstall the versions locker installs of express and connect, but I deactivated them and activated the express@1.0.7 and connect@0.5.7 versions

And Locker works!! thanks again mates

**Comment by temas** [comment] 2011-03-20 14:52
Glad you got it going. We'll be working to make the install/startup process easier real soon. 

--temas

**Comment by sambirk** [comment] 2011-03-22 17:26
I have installed and activated express@1.0.7 and connect@0.5.7 on node@v0.4.3 with npm@0.3.17 and no luck getting Locker running using Ubuntu Server 10.10.

Terminal dump here https://gist.github.com/881588

Going to install node@v0.4.0 via nvm as suggested by seacron now

**Comment by temas** [comment] 2011-03-22 17:31
Can you try clearing out the older versions of connect?  Really odd issue, because it all looks like it should be fine.

**Comment by sambirk** [comment] 2011-03-22 19:39
nope that didn't solve it

**Comment by temas** [comment] 2011-03-22 19:45
Did you try the deactivate -> reactivate process that magg did?

**Comment by sambirk** [comment] 2011-03-22 19:49
Yes I did but that didn't help either.
I'm using virtualbox on a windows 7 host so I'm creating a new vm as I type and starting from scratch to make sure nothing borked somehow.

**Comment by temas** [comment] 2011-03-22 20:14
How peculiar, let me know how that goes and what the VM setup is.  I'll recreate it locally if there's still an issue.

**Comment by temas** [comment] 2011-03-24 15:18
Any luck samBiotic?

**Comment by ctide** [comment] 2011-03-24 16:47
Same for me:

https://gist.github.com/90f5c26367e699ce76f0

Fresh node install, OSX 10.6.6.

**Comment by ctide** [comment] 2011-03-24 16:52
Also worth noting that I installed the specific versions mentioned here (connect@0.5.7 and express@1.0.7) and had the same issue.

**Comment by sambirk** [comment] 2011-03-24 20:14
temas,

new ubuntu server 32bit 10.10 virtualbox install with openssh server the only thing install from installation media.

then performed the following in an attempt to get a working Locker.

```
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install git-core curl build-essential openssl libssl-dev
git clone https://github.com/joyent/node.git
cd node
git fetch --all
git tag
git checkout v0.4.3
./configure
make
make install
node -v
cd ..
git clone git://github.com/quartzjer/Locker.git
cd Locker
curl http://npmjs.org/install.sh | npm_install=rc sh
npm -v
npm ls #all modules unmet dependency
npm install #sqlite1.0.3 fails to build
npm ls #sqlite unmet dependancy
sudo apt-get install libsqlite-dev
npm ls #sqlite unmet dependency
npm install #sqlite1.0.3 fails to build again
curl http://npmjs.org/install.sh | sh #downgrade npm to latest stable 0.3.17
npm install #sqlite1.0.3 fails to build again
```

final npm install terminal dump is here: https://gist.github.com/885738

I don't think this is an npm issue as it happened with 1rc and 0.3.17

filed an issue on node-sqlite repository: https://github.com/orlandov/node-sqlite/issues#issue/27

I could just have missing dependencies that I could install with apt?

**Comment by sambirk** [comment] 2011-03-25 04:05
Ok I've fixed the sqlite dependency (it needed libsqlite3-dev)

Here's a full Ubuntu 10.10 install guide using nvm as it made life easier 3rd time around!

```
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install vim git-core libssl-dev curl build-essential libsqlite3-dev
git clone git://github.com/creationix/nvm.git ~/.nvm
. ~/.nvm/nvm.sh
vim .bashrc #add the line [. ~/.nvm/nvm.sh] without brackets
nvm sync
nvm install stable
nvm use stable
node -v #v0.4.3
npm -v #0.3.17
nvm alias default v0.4.3
git clone git://github.com/quartzjer/Locker.git
cd Locker
npm install
node locker.js #Cannot find module 'connect/middleware/router'
npm install express@1.0.7
npm install connect@0.5.7
npm ls installed
node locker.js #works
```

**Comment by seancron** [comment] 2011-03-25 06:24
I just noticed that the Express github has some details about compatibility: https://github.com/visionmedia/express

They say that "Express 1.x is compatible with node 0.2.x and connect < 1.0" and "Express 2.x is compatible with node 0.4.x and connect 1.x".

Since we're using `node 0.4.x`, shouldn't we be using `express 2.x` and `connect 1.x`? For anyone who is interested, here are the details of the express 1.x to 2.x migration: http://expressjs.com/migrate.html

**Comment by temas** [comment] 2011-03-25 06:45
I've updated the package.json and reverified everything against a fresh build for latest node 0.4.3, express 2.1.0 and connect 1.1.4.  It should all be fixed now.

**Comment by sambirk** [comment] 2011-03-25 13:29
great stuff

**Comment by smurthas** [comment] 2011-03-25 16:15
Everything is working on my side - is it all good with you guys?

**Comment by temas** [comment] 2011-03-25 16:49
If I can get one more confirmation of a clean install that is running correctly I'm going to close this out.

**Comment by ctide** [comment] 2011-03-25 16:50
Works for me, thanks!

**Comment by seancron** [comment] 2011-03-25 16:51
I think you can close this. Fresh node v0.4.2 install, `npm install` and `node locker.js` worked with no errors.

**Comment by temas** [comment] 2011-03-25 18:24
Thanks for all the diligence in getting this sorted.

**Closed as completed by temas** 2011-03-25 18:24 UTC
