### ISSUE TITLE
UI greys out when backend goes away

### ISSUE THREAD

**Issue by smurthas** [LockerProject/Locker#461] opened 2011-11-21 22:25 UTC
If the locker is killed while the UI is open, the overlay appears and sometimes shows the welcome dialog.

**Comment by ctide** [comment] 2011-11-21 22:51
Dupe of #446

**Comment by ctide** [comment] 2011-11-21 22:52
Not a dupe of #446

**Comment by smurthas** [comment] 2011-11-22 00:56
:)

**Comment by smurthas** [comment] 2011-11-29 19:23
@ctide, assigned to you to make sure this gets fixed with the new UI, not the old one.

**Comment by ctide** [comment] 2012-01-04 00:50
fixed in new UI

**Closed as completed by ctide** 2012-01-04 00:50 UTC
