### ISSUE TITLE
Can't connect to any services. Authentication fails.

### ISSUE THREAD

**Issue by zencuke** [LockerProject/Locker#511] opened 2011-12-19 21:48 UTC
I attempted to connect to facebook, twitter and github. All failed to authenticate. I asked for help on #lockerProject and temas
got me past some simple misunderstandings but authentication still failed. The first gist is a dump of the stdout of ./locker. The second is the irc thread so you can see what temas has already walked me through plus some possible relevant background.

gist.github.com/1499009.git

gist.github.com/1499033.git

**Comment by zencuke** [comment] 2011-12-19 21:52
I forgot to mention. The log has two errors in it. node failure to open clucene library (twice) gthen 

19 Dec 12:24:30 - error: Failed to auth github - {"error":"Couldn't authenticate you"}
19 Dec 12:24:37 - info: delaying quiesce for useui
19 Dec 12:24:45 - error: Failed to auth github - {"error":"Couldn't authenticate you"}
19 Dec 12:25:02 - error: { stack: [Getter/Setter],

There are quite a few warnings in the log also. See the log for details.

**Comment by quartzjer** [comment] 2011-12-21 16:01
I'm going to close #467 and mark it as a duplicate of this one, so we can work through the issue on a new thread here.  As I mentioned in the other issue, ping me direct and I'll send you some test keys to try, thanks!

**Comment by merc3po** [comment] 2012-01-31 01:12
What's the status of this?

**Comment by quartzjer** [comment] 2012-01-31 01:13
I believe this has all been resolved now, @zencuke can re-open it or add more detail if there's still any problems with the auth, thx!

**Closed as completed by quartzjer** 2012-01-31 01:13 UTC
Labels: bug
