### ISSUE TITLE
Photos unhandled feed/instagram

### ISSUE THREAD

**Issue by smurthas** [LockerProject/Locker#509] opened 2011-12-19 00:00 UTC
I get this error stream every time I connect Instagram:

```
18 Dec 15:54:31 - error: unhandled feed/instagram
[photos] 18 Dec 15:54:31 - error: unhandled feed/instagram
[photos] 18 Dec 15:54:31 - error: unhandled feed/instagram
```

The photos still end up in the photos collection, so it might just be incorrect logging.

**Comment by ctide** [comment] 2012-01-04 01:11
Dupe of #526

**Closed as completed by ctide** 2012-01-04 01:11 UTC
