### ISSUE TITLE
Can't see API token

### ISSUE THREAD

**Issue by merc3po** [LockerProject/Locker#850] opened 2012-02-20 17:14 UTC
Clicks the button and doesn't get anything.

**Comment by amcjen** [comment] 2012-02-20 23:18
Checked this in Chrome, in Safari, and in Firefox, and all three show me my API token when clicking on the link.  Is it still broken for you?

**Comment by merc3po** [comment] 2012-02-21 00:33
I'll email him and ask - this was posted to the forums. I'll cc you.

**Comment by smurthas** [comment] 2012-02-22 18:46
This is a dupe of #828

**Closed as completed by smurthas** 2012-02-22 18:46 UTC
Labels: bug
