### ISSUE TITLE
Counts for photos, people, links sometimes don't appear

### ISSUE THREAD

**Issue by mdz** [LockerProject/Locker#283] opened 2011-10-06 19:53 UTC
Even after a page refresh!

**Comment by temas** [comment] 2011-10-06 19:54
Another case we're seeing now is 0s except for a collection that just updated.

**Comment by smurthas** [comment] 2011-10-20 23:37
hrmm, the last comment says closed, but the issue is open? I believe this is closed by taking out websockets (and switching to JSONP). @temas, is that correct?

**Comment by temas** [comment] 2011-10-21 04:50
Odd, you are correct, trying to close it again.

**Closed as completed by temas** 2011-10-21 04:50 UTC
