### ISSUE TITLE
Location of apikeys.json not explained

### ISSUE THREAD

**Issue by elsmorian** [LockerProject/Locker#288] opened 2011-10-07 11:15 UTC
At first run, the user is prompted to insert API information into apikeys.json, but is not told where to find this file.

**Comment by elsmorian** [comment] 2011-10-07 11:19
(On the main page, it is explained in the linked wiki, so maybe not such a problem :)

**Comment by othiym23** [comment] 2011-10-10 17:02
This is a dupe of issue #296 -- the documentation around setting up and running standalone lockers is badly out of date.

**Closed as completed by othiym23** 2011-10-10 17:02 UTC
