### ISSUE TITLE
can't get node-clucene to build properly on OS X 10.7.2

### ISSUE THREAD

**Issue by zencuke** [LockerProject/Locker#467] opened 2011-11-28 03:25 UTC
I have spend the last two days trying to install locker. First I tried lockerbox.sh. Then I followed the link to "Detailed Install Instructions." Half the commands on this page failed for one reason or another: Macports/fink incompatability; node version incompatability with npm; npm can't cope with some of the dependencies in Locker/package.json. Apparently some of the specified package versions in this file are no longer supported by the current npm. I have gotten so many different errors and tried so many workarounds that I have probably created incompatibilities between all the things locker depends on. I believe I finally have the correct versions of most things. At least ./checkEnv.sh doesn't complain about the versions it finds. However npm install still fails. 

npm ERR! error installing unshortener@0.0.8     at Request._callback (/usr/local/lib/node_modules/npm/lib/utils/npm-registry-client/request.js:180:12)
npm ERR! error installing unshortener@0.0.8     at Request.callback (/usr/local/lib/node_modules/npm/node_modules/request/main.js:99:22)

I most recently deleted the Locker directory and tried lockerbox.sh again hoping iot would succeed it the dependencies were already installed, I got the following results:

1) curl https://github.com/LockerProject/lockerbox/blob/master/lockerbox.sh > lockerbox.sh
Rather than download the script this commands downloads the html web page that contains it. I fixed this by going to that page and clicking on raw and then downloading the file with my browser.

2) papas-macintosh:~ steven$ ./lockerbox.sh 
... successful progress reports clipped ...
./lockerbox.sh: line 58: pkg-config: command not found
CLucene not found!

About to download, build, and install locally CLucene.
This could take a while....git://clucene.git.sourceforge.net/gitroot/clucene/clucene already downloaded.
-- The C compiler identification is GNU
-- The CXX compiler identification is GNU
-- Checking whether C compiler has -isysroot
-- Checking whether C compiler has -isysroot - yes
-- Checking whether C compiler supports OSX deployment target flag
-- Checking whether C compiler supports OSX deployment target flag - yes
-- Check for working C compiler: /Developer/usr/bin/gcc

Make Error at /Applications/CMake 2.8-6.app/Contents/share/cmake-2.8/Modules/CMakeTestCCompiler.cmake:52 (MESSAGE):
  The C compiler "/Developer/usr/bin/gcc" is not able to compile a simple
  test program.

This is probably because Apple has restructured where and how it installs these tools in the latest version of Xcode for Lion. In particular /Developer/usr/bin/gcc doesn't exist. However I'm not sure what to do about it. clucene isn't exactly the simplest thing to install manually but I am looking into it. Is this the right approach? I've noticed that some other projects seem to have trouble coping with the newest xcode release. I have been assuming up till now that my problems were either operator error or something weird about my configuration but my problems are so egregious that I am beginning to wonder if I am the first person to attempt this with the newest xcode. Should I expect this to work?

**Comment by quartzjer** [comment] 2011-11-28 04:06
First, thank you for such thorough feedback (and persistence!), super helpful and appreciated.  I suspect all of us are using the Xcode and systems that have been upgraded, not a fresh start, so it looks like there's definitely some new things we need to fix :(

Also, unshortener was just recently removed from the package.json as it's not used anymore, have you tried updating from git master to see if that helps, and were there any other npm dependencies failing?

**Comment by zencuke** [comment] 2011-11-28 10:33
Unfortunately after everything I have done recently, especially the manual update of various dependencies, I don't really qualify as a "clean" install. My original problems seem to have been caused by various old macport and fink installs that were copied to my new Mac as part of the original Lion configure process. Among other things they were blocking brew from working. Also the fink version of tar was causing the npm install script to fail. With help from the npm maintainer and 'brew doctor' I believe I have finally managed to delete most of the offending vestiges of macports and fink. In the process I manually installed the current version of node which Locker/package.json didn't like. It took me a while to back out of that.

My original git clone from a couple of days ago had a dependency problem with npm:1.0.27. That version is apparently no longer supported (npm failed on that dependency in a rather unhelpful way) but that seems to have been fixed in the current git repositiory. package.json now references npm:1.0.106 which is the current version. After the lockerbox.sh attempt described above I manually reloaded with:

% rm Locker; git clone https://github.com/LockerProject/Locker.git; cd Locker;checkEnv.sh 
Python version 2.7.1 found.
Node.js version 0.4.9 found.
npm version 1.0.106 found.
mongoDB version 2.0.1 found.

and tried npm install again. This also failed in the CLucene build but with a different error than the above described lockerbox.sh attempt. This failure also seems to be gcc version related. This pass seems to find gcc but has compile problems using the gcc version found. Here is the log extract:

... successful progress reports clipped ...
Checking for library clucene-core        : 'configure' finished successfully (0.497s)
Waf: Entering directory `/Users/steven/Locker/node_modules/daemon/build'
[1/2] cxx: src/daemon.cc -> build/Release/src/daemon_1.o
yes 
'configure' finished successfully (2.238s)
Waf: Entering directory`/Users/steven/Locker/node_modules/clucene/build'
[1/2] cxx: src/clucene_bindings.cpp -> build/Release/src/clucene_bindings_1.o
[2/2] cxx_link: build/Release/src/daemon_1.o -> build/Release/daemon.node
Waf: Leaving directory `/Users/steven/Locker/node_modules/daemon/build'
'build' finished successfully (2.882s)
../src/clucene_bindings.cpp: In static member function ‘static v8::Handle<v8::Value> Lucene::AddDocumentAsync(const v8::Arguments&)’:
../src/clucene_bindings.cpp:286: error: invalid conversion from ‘int (*)(eio_req*)’ to ‘void (*)(eio_req*)’
../src/clucene_bindings.cpp:286: error:   initializing argument 1 of ‘eio_req* eio_custom(void (*)(eio_req*), int, int (*)(eio_req*), void*)’
../src/clucene_bindings.cpp: In static member function ‘static v8::Handle<v8::Value> Lucene::DeleteDocumentAsync(const v8::Arguments&)’:
../src/clucene_bindings.cpp:431: error: invalid conversion from ‘int (*)(eio_req*)’ to ‘void (*)(eio_req*)’
../src/clucene_bindings.cpp:431: error:   initializing argument 1 of ‘eio_req* eio_custom(void (*)(eio_req*), int, int (*)(eio_req*), void*)’
../src/clucene_bindings.cpp: In static member function ‘static v8::Handle<v8::Value> Lucene::DeleteDocumentsByTypeAsync(const v8::Arguments&)’:
../src/clucene_bindings.cpp:530: error: invalid conversion from ‘int (*)(eio_req*)’ to ‘void (*)(eio_req*)’
../src/clucene_bindings.cpp:530: error:   initializing argument 1 of ‘eio_req* eio_custom(void (*)(eio_req*), int, int (*)(eio_req*), void*)’
../src/clucene_bindings.cpp: In static member function ‘static v8::Handle<v8::Value> Lucene::SearchAsync(const v8::Arguments&)’:
../src/clucene_bindings.cpp:642: error: invalid conversion from ‘int (*)(eio_req*)’ to ‘void (*)(eio_req*)’
../src/clucene_bindings.cpp:642: error:   initializing argument 1 of ‘eio_req* eio_custom(void (*)(eio_req*), int, int (*)(eio_req*), void*)’
../src/clucene_bindings.cpp: In static member function ‘static v8::Handle<v8::Value> Lucene::OptimizeAsync(const v8::Arguments&)’:
../src/clucene_bindings.cpp:774: error: invalid conversion from ‘int (*)(eio_req*)’ to ‘void (*)(eio_req*)’
../src/clucene_bindings.cpp:774: error:   initializing argument 1 of ‘eio_req* eio_custom(void (*)(eio_req*), int, int (*)(eio_req*), void*)’
Waf: Leaving directory`/Users/steven/Locker/node_modules/clucene/build'
Build failed:  -> task failed (err #1): 
    {task: cxx clucene_bindings.cpp -> clucene_bindings_1.o}
npm ERR! error installing clucene@0.2.3 Error: clucene@0.2.3 install: `node-waf configure build`
npm ERR! error installing clucene@0.2.3 `sh "-c" "node-waf configure build"` failed with 1
npm ERR! error installing clucene@0.2.3     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/exec.js:49:20)
npm ERR! error installing clucene@0.2.3     at ChildProcess.emit (events.js:67:17)
npm ERR! error installing clucene@0.2.3     at ChildProcess.onexit (child_process.js:192:12)
npm ERR! clucene@0.2.3 install: `node-waf configure build`
npm ERR! `sh "-c" "node-waf configure build"` failed with 1
npm ERR! 
npm ERR! Failed at the clucene@0.2.3 install script.
npm ERR! This is most likely a problem with the clucene package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls clucene
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System Darwin 11.2.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/steven/Locker
npm ERR! node -v v0.4.9
npm ERR! npm -v 1.0.106
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/steven/Locker/npm-debug.log
npm not ok

**Comment by zencuke** [comment] 2011-11-30 04:45
OK the status seems to be that anyone with a recently purchased Mac or anyone running Lion who updates to xCode 4.2 can't install Locker because the npm CLucene install fails. Only users who installed before xCode 4.2 are able to run because their previous clucene build is still valid. Strangely brew has no problem installing CLucene but the npm install process doesn't seem to look for that.

Too bad. Locker sounded interesting. Hopefully I'll get notified when current Macs are supported again and this issue gets closed as a result. I suspect that Mac users are a small percentage of the locker world so the priority of this issue is low. Sigh...

**Comment by ctide** [comment] 2011-12-02 02:06
What happens if you do the following:

[ctide@Chris-Burkharts-MacBook-Pro-2 /development/Locker] [master]:~$ **brew uninstall --force clucene**
Uninstalling clucene...
[ctide@Chris-Burkharts-MacBook-Pro-2 /development/Locker] [master]:~$ **brew install clucene --HEAD**
==> Cloning git://clucene.git.sourceforge.net/gitroot/clucene/clucene
Cloning into /Users/ctide/Library/Caches/Homebrew/clucene--git...
remote: Counting objects: 4900, done.
remote: Compressing objects: 100% (3361/3361), done.
remote: Total 4900 (delta 2342), reused 3768 (delta 1491)
Receiving objects: 100% (4900/4900), 5.08 MiB | 740 KiB/s, done.
Resolving deltas: 100% (2342/2342), done.
==> cmake . -DCMAKE_INSTALL_PREFIX='/usr/local/Cellar/clucene/HEAD' -DCMAKE_BUILD_TYPE=None -Wno-dev
==> make install
/usr/local/Cellar/clucene/HEAD: 300 files, 3.9M, built in 86 seconds
[ctide@Chris-Burkharts-MacBook-Pro-2 /development/Locker] [master]:~$ **npm install clucene**
npm WARN async@0.1.9 package.json: bugs['web'] should probably be bugs['url']
npm WARN htmlparser2@1.0.0 package.json: bugs['web'] should probably be bugs['url']
npm WARN jslint@0.1.0 package.json: bugs['web'] should probably be bugs['url']
npm WARN mongodb@0.9.6-15 package.json: bugs['web'] should probably be bugs['url']
npm WARN request@2.1.1 package.json: bugs['web'] should probably be bugs['url']
npm WARN wrench@1.1.0 package.json: bugs['web'] should probably be bugs['url']
npm WARN xmlbuilder@0.1.2 package.json: bugs['web'] should probably be bugs['url']

> clucene@0.2.3 install /development/Locker/node_modules/clucene
> node-waf configure build

Setting srcdir to                        : /development/Locker/node_modules/clucene 
Setting blddir to                        : /development/Locker/node_modules/clucene/build 
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : ok /Users/ctide/.node_libraries 
Checking for node prefix                 : ok /usr/local/Cellar/node/0.4.10 
Checking for library clucene-core        : yes 
'configure' finished successfully (0.136s)
Waf: Entering directory `/development/Locker/node_modules/clucene/build'
[1/2] cxx: src/clucene_bindings.cpp -> build/default/src/clucene_bindings_1.o
[2/2] cxx_link: build/default/src/clucene_bindings_1.o -> build/default/clucene.node
Waf: Leaving directory`/development/Locker/node_modules/clucene/build'
'build' finished successfully (1.384s)
clucene@0.2.3 ./node_modules/clucene

**Comment by zencuke** [comment] 2011-12-02 11:47
**Same thing.**

papas-macintosh:~ steven$ **brew uninstall --force clucene**
Uninstalling clucene...
papas-macintosh:~ steven$ **brew install clucene -HEAD**
==> Cloning git://clucene.git.sourceforge.net/gitroot/clucene/clucene
Updating /Users/steven/Library/Caches/Homebrew/clucene--git
==> cmake . -DCMAKE_INSTALL_PREFIX='/usr/local/Cellar/clucene/HEAD' -DCMAKE_BUIL
==> make install
/usr/local/Cellar/clucene/HEAD: 301 files, 3.9M, built in 101 seconds
papas-macintosh:~ steven$ **npm install clucene**

> clucene@0.2.3 install /Users/steven/node_modules/clucene
> node-waf configure build

Setting srcdir to                        : /Users/steven/node_modules/clucene 
Setting blddir to                        : /Users/steven/node_modules/clucene/build 
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/local/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /usr/local/Cellar/node/0.6.2 
Checking for library clucene-core        : yes 
'configure' finished successfully (0.271s)
Waf: Entering directory `/Users/steven/node_modules/clucene/build'
[1/2] cxx: src/clucene_bindings.cpp -> build/Release/src/clucene_bindings_1.o
../src/clucene_bindings.cpp: In static member function ‘static v8::Handle<v8::Value> Lucene::AddDocumentAsync(const v8::Arguments&)’:
../src/clucene_bindings.cpp:286: error: invalid conversion from ‘int (*)(eio_req*)’ to ‘void (*)(eio_req*)’
../src/clucene_bindings.cpp:286: error:   initializing argument 1 of ‘eio_req* eio_custom(void (*)(eio_req*), int, int (*)(eio_req*), void*)’
../src/clucene_bindings.cpp: In static member function ‘static v8::Handle<v8::Value> Lucene::DeleteDocumentAsync(const v8::Arguments&)’:
../src/clucene_bindings.cpp:431: error: invalid conversion from ‘int (*)(eio_req*)’ to ‘void (*)(eio_req*)’
../src/clucene_bindings.cpp:431: error:   initializing argument 1 of ‘eio_req* eio_custom(void (*)(eio_req*), int, int (*)(eio_req*), void*)’
../src/clucene_bindings.cpp: In static member function ‘static v8::Handle<v8::Value> Lucene::DeleteDocumentsByTypeAsync(const v8::Arguments&)’:
../src/clucene_bindings.cpp:530: error: invalid conversion from ‘int (*)(eio_req*)’ to ‘void (*)(eio_req*)’
../src/clucene_bindings.cpp:530: error:   initializing argument 1 of ‘eio_req* eio_custom(void (*)(eio_req*), int, int (*)(eio_req*), void*)’
../src/clucene_bindings.cpp: In static member function ‘static v8::Handle<v8::Value> Lucene::SearchAsync(const v8::Arguments&)’:
../src/clucene_bindings.cpp:642: error: invalid conversion from ‘int (*)(eio_req*)’ to ‘void (*)(eio_req*)’
../src/clucene_bindings.cpp:642: error:   initializing argument 1 of ‘eio_req* eio_custom(void (*)(eio_req*), int, int (*)(eio_req*), void*)’
../src/clucene_bindings.cpp: In static member function ‘static v8::Handle<v8::Value> Lucene::OptimizeAsync(const v8::Arguments&)’:
../src/clucene_bindings.cpp:774: error: invalid conversion from ‘int (*)(eio_req*)’ to ‘void (*)(eio_req*)’
../src/clucene_bindings.cpp:774: error:   initializing argument 1 of ‘eio_req* eio_custom(void (*)(eio_req*), int, int (*)(eio_req*), void*)’
Waf: Leaving directory`/Users/steven/node_modules/clucene/build'
Build failed:  -> task failed (err #1): 
    {task: cxx clucene_bindings.cpp -> clucene_bindings_1.o}
npm ERR! error installing clucene@0.2.3 Error: clucene@0.2.3 install: `node-waf configure build`
npm ERR! error installing clucene@0.2.3 `sh "-c" "node-waf configure build"` failed with 1
npm ERR! error installing clucene@0.2.3     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/exec.js:49:20)
npm ERR! error installing clucene@0.2.3     at ChildProcess.emit (events.js:67:17)
npm ERR! error installing clucene@0.2.3     at ChildProcess.onexit (child_process.js:192:12)
npm ERR! clucene@0.2.3 install: `node-waf configure build`
npm ERR! `sh "-c" "node-waf configure build"` failed with 1
npm ERR! 
npm ERR! Failed at the clucene@0.2.3 install script.
npm ERR! This is most likely a problem with the clucene package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls clucene
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System Darwin 11.2.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "clucene"
npm ERR! cwd /Users/steven
npm ERR! node -v v0.4.9
npm ERR! npm -v 1.0.106
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/steven/npm-debug.log
npm not ok
papas-macintosh:~ steven$

**Comment by zencuke** [comment] 2011-12-02 12:04
That is: It is the same except I seem to have remnants to two different node installs. The node in the execute path is 4.9 but the configure finds /usr/local/Cellar/node/0.6.2. That's consistant though. I originally installed the current version then installed 4.9 because of instructions I saw somewhere on the lockerProject site.

**Comment by ctide** [comment] 2011-12-02 13:19
OK, that makes sense.  The clucene module will most likely not build against node 0.6 source.  We haven't put too much time into node 0.6 compatibility since it's blocked on a few other modules we use (such as node-http-proxy).  I'd recommend removing node 0.6 entirely, and installing an 0.4.x version from source.

Sorry about that, we hope to get everything patched up for 0.6.x soon!

**Comment by zencuke** [comment] 2011-12-02 20:39
I had installed node 4.9 explicitly to avoid problems. The incompatibility
was noted somewhere and actually caused more problems than just clucene.
However I did that from source in my home directory. I didn't know how to
tell brew to delete the previous install. The source code install replaced
the executable but not the libraries from the brew install. There is
probably a way to tell the npm install where to look for the node
libraries. When I get home I will figure out how to uninstall the node 6
libraries and try again.

What exactly is node anyhow. The descriptions on the web site are somewhat
vague and general. ("scalable network programs" covers a lot of ground.)
What kind of packages tend to use it?

On Fri, Dec 2, 2011 at 8:19 AM, Chris Burkhart <
reply@reply.github.com

**Comment by zencuke** [comment] 2011-12-05 18:16
After a torturous process I finally tried to clean everything out and start over. Actually I have done this several times learning more each time. I start by updating brew (there a couple of recent updates to brew to address issues I reported.) Then I use brew to install the node-0.4.9 (node is now up to 0.4.12 but I haven't tried that yet)  using what I learned about installing older versions of node from brew. (The recently added brew versions command points the way.) Next I install clucene with brew. If that all works I try lockerbox.sh again. The last attempt everything including clucene seemed to builld and install and the script actually launches locker. However lockerbox.sh reported error messages about not being able to link clucene. When I run the test script from the tests directory I get lots of errors which seem to be clucene related so that is at least consistant.

Have I missed anything about telling node/ locker how to find clucene? Are there environment variables that need to be set?

Note: I may have two installs of clucene with possible conflicts between them. I installed the current version with brew and it looks like npm install built and installed another version. Unless I get better advice here my next step will be to start over again this time without installing clucene with brew.

Sorry about not attaching logs but I am not at my machine right now. If more information is needed I will attach logs in a comment when I get back to my Macintosh.

Note2: For a script that claims to work out of the box lockerbox.sh seems awfully fragile. It has been 8 days since I opened this ticket. Since then I have invested massive amounts of energy trying to debug brew/ node/npm/lockerbox.sh install problems and even with lots help from this group in the form of comments on this issue and a similar support for an issue I opened against brew I still don't have locker running in a useful way. I am an experienced developer. It seems that that is both bad and good for using lockerbox.sh. The good side is that I can help debug these problems as I find them. The bad side is that I have probably caused most of these problems by doing things like previously installing various MacPorts and fink utilities (brew definitely has problems coexisting with either.) Apple obsoleting non llvm versions of gcc didn't help either. xCode no longer installs gcc4.2.

I hope I am not dissapointed when(if?) I actually get locker working. From outside it sure looks like a game changer and the vision speaks directly to me. Maybe you have to live in SF to be part of this revolution.

**Comment by quartzjer** [comment] 2011-12-06 21:42
clucene has been such a pain, very sorry :( As such, it's going away soon, there's a pull request open to replace it with something that will install normally like any other npm module.  Think that will help?

I live in Iowa :)

**Comment by No9** [comment] 2011-12-10 22:21
Hi I have a pull request with node-clucene that resolves this.

https://github.com/erictj/node-clucene/pull/17

**Comment by quartzjer** [comment] 2011-12-10 23:19
Thanks Anton! Related, there's also a pull request that will land soon
that replaces clucene with sqlite-fts, which installs normally via npm
:)
https://github.com/LockerProject/Locker/pull/486

On Sat, Dec 10, 2011 at 4:21 PM, Anton Whalley
reply@reply.github.com
wrote:

**Comment by othiym23** [comment] 2011-12-12 22:02
FWIW, zencuke, the Singly dev team is doing all our development work on Macs running Lion. ;)

**Comment by zencuke** [comment] 2011-12-12 23:27
I understand. However I suspect that the development team doesn't spend
much time installing on virgin Macs and they probably don't have fink or
MacPorts installed. The various package managers tend to step on each
other.  'brew doctor' complained loudly when I finally ran it. I suspect
that the principal reason the dev team didn't see the clucene install
problem with the new xCode was that they had a good version installed that
awas built with the previous version of xCode that still had gcc4.2.
lockerbox found the dependency satisfied and didn't attempt to reinstall.
Maybe lockerbox needs a -clean option. In my experience unless they are
involved with QA developers tend to stick with what works.

Unfortunately this means that while most of my problems were probably
caused by conditions on my machine that the dev team never sees I have no
clue how to get my machine to a state where lockerProject will successfully
install. I haven't tried wiping my disk and starting over. I don't want
Locker badly enough for that.

I suppose I should create a virgin bootable partition somewhere but with no
optical drive and Apple no longer supplying install disks I'm not sure how
to do that. I'm sure it is documented somewhere but I have already spent a
massive amount of time trying to install locker and I'm frankly burned out.

Lockerbox looked like a nice clean easy install.  I carefully followed the
instructions. The first thing that happened was:

% curl https://raw.github.com/*LockerProject*/lockerbox/master/*lockerbox*.*
sh*

instead of downloading lockerbox.sh curl downloaded the html code which
displayed lockerbox.sh. That wasn't too tough to work around but It wasn't
a good sign. Obviously no one on the dev team had followed these
instructions lately. The next problem I had was a node.js version
incompatibility with npm and the brew incompatibility with MacProjets and
the clucene incompatibility with the latest xCode and I had an old version
of git which caused brew to fail and the brew doc didn't mention the
recently added (August) versions command so I managed to trash my brew
repository trying to fix brew so it would install the version of node.js
required. etc. etc. Before this effort I had never heard of node.js, npm,
clucene or brew but I'm an experienced developer and really wanted to try
Locker and maybe write my own applications for it so I rolled up my
sleeves. Of course with a total lack of knowledge I probably made things
worse as often as I made them better. After devoting almost two weeks of my
discretionary time on this getting help (i.e. annoying people with my naive
questions) from this group, the npm developer and the brew developer on
this supposedly simple task I finally had to get back to other obligations.

It is too bad because LockerProject sounds tremendously exciting and I
think I could have contributed.

On Mon, Dec 12, 2011 at 5:02 PM, Forrest L Norvell <
reply@reply.github.com

**Comment by othiym23** [comment] 2011-12-13 01:48
I'm sorry you've had such a tough time getting your locker up and running! The project is under active development and we're moving pretty fast, so there are definitely some rough edges.

I do have some comments on some of the issues you've seen:
- Node is an event-driven / asynchronous programming system built on top of Google's V8 Javascript runtime. People tend to use it for web-based systems like chat systems or high-throughput RESTful APIs, because the asynchronous programming model adapts well to high-throughput / low-latency network programming.
- I myself am running XCode 4.2, and have built node a couple times since then without issue (as I switched from using Homebrew to nvm to manage my node installations). It's possible there's some kind of clang issue I'm not seeing due to how I have my build environment configured, but I haven't been able to reproduce your issue.
- I just ran `curl https://raw.github.com/LockerProject/lockerbox/master/lockerbox.sh` and got back the correct (non-HTML wrapped) version of the lockerbox script. Are you sure you ran the request against raw.github.com?
- CLucene is a difficult component to build, especially as we're using a pre-release / direct from VCS version of the code. That said, it too has built just fine with the latest official Apple toolchain (using Homebrew / 'brew install --HEAD clucene'). As @quartzjer mentioned above, he's in the process of replacing CLucene with SQLite's full-text search support, which will considerably simplify that portion of the build process.
- I haven't seen the issues you're having with npm. It's true that npm is moving to node 0.6.x fairly quickly, but until some fixes to some of the core HTTP modules land (in the next week or two), the locker codebase is stuck on node 0.4.x, and npm is still working for us. (As an aside, I've used node versions up through 0.4.11 without difficulty.)

If you're interested in giving things another shot, I'd suggest uninstalling any versions of node you may have installed through any of Fink, Macports, and Homebrew, and then building and installing node 0.4.9 or .10 from source, either via lockerbox.sh or from the command line. If you wait another day or two, @quartzjer's new search code will be in master, and you won't have to deal with CLucene issues anymore anyway.

Thanks for your patience, and for giving us a look-see!

**Comment by zencuke** [comment] 2011-12-13 04:42
Sorry. I should have mentioned that the curl problem has been fixed long
since. In my frustration I was whining about old problems and should have
instead given credit to whoever fixed it. It got fixed immediately after I
posted the issue. Quite a few things that orignally gave me trouble have
been fixed. I'm afraid I was overeacting to your lighthearted comment that
the Singly developers used the same version of OS X and xCode that I have
with the implicit suggestion that no one else was having problems. Through
this process I have frequently wondered if I was finally entering my
dotage. The number of unrelated problems I have had is hard even for me to
believe. Thankfully I have had plenty of help, both here and from brew and
npm developers. The brew developer made several fixes for issues I posted,
sometimes within minutes of my post. I got in the habit of doing git update
almost between every brew command to make sure I got the latest fix. Some
obsolete dependencies have since been removed from lockerbox's package.json
which helped a lot. As a matter of fact there may be no issues left other
than the self inflicted corruption of my system caused by my misguided
attempts to work through these issues. In fact my last lockerbox run (a
week ago) was close. The build part finally succeeded and it even launched
locker although it was pretty useless because of a new CLucene problem.
lockerbox built CLucene successfully but locker found a different (newer
and incompatible?) version at runtime, something I had probably installed
along the way. In fact if someone could explain to me how a specific
version of CLucene is bound to locker (environment variable? default path?
Is it a library which gets linked or a command that gets run?) that might
get me over the hump. Or maybe I should just wait for @quartzjer's changes.

In retrospect I think all of my real (as opposed to self inflicted)
problems were version dependency issues starting with very old MacPorts and
fink installs of various tools that ended up interfering with brew and npm.
For example both git and tar were old enough to cause spurious failures.
The problem with letting the Mac installer upgrade a new Mac with an old
boot disk is that a lot of historical baggage comes along with the valuable
personal data.

On Mon, Dec 12, 2011 at 8:48 PM, Forrest L Norvell <
reply@reply.github.com

**Comment by ckemmler** [comment] 2011-12-13 13:13
Hey, just to cheer things up a bit: I was lucky enough to be able to build and deploy lockerbox yesterday in less than 2 hours :-) I agree though that it was far from a smooth process and that I did require some help (kindly provided by othiym23 on irc) to get everything working.

**Comment by zencuke** [comment] 2011-12-19 14:16
I'm home for the holidays so I finally had time to try again. I again deleted lockerbox and started from the beginning (curl url | bash.). It worked this time including the build of CLucene. Thanks for the help. It is not clear how much of my trouble was preexisting conditions on my Mac that I needed to fix first and how much was fixed by cleanup of the lockerbox install process but either way thanks for the help. I think most of my issues should have been directed to the irc channel though I haven't used irc in years. I guess it is time to figure it out again.

Thanks

**Comment by zencuke** [comment] 2011-12-21 08:04
Actually it didn't work. The build passed which I suppose technically closes this issue however although ./Iocker launched but nothing authenticates. I've tried twitter, facebook and github each with a different failure mode. I just clicked on the twitter icon and got:

21 Dec 02:52:14 - warn: Could not find Apps/HelloPlaces/img/viewer-icon.png
21 Dec 02:52:14 - warn: Could not find Apps/FoursquareStats/img/viewer-icon.png
21 Dec 02:52:14 - warn: Could not find Apps/HelloPlaces/img/viewer-icon.png
21 Dec 02:52:20 - error: { stack: [Getter/Setter],
  arguments: undefined,
  type: undefined,
  message: '[object Object]' }
21 Dec 02:52:20 - error: 'Error: [object Object]\n    at /Users/steven/lockerbox/Locker/Ops/webservice-synclets-auth.js:160:31\n    at /Users/steven/lockerbox/Locker/Connectors/Twitter/twitter_client.js:131:14\n    at /Users/steven/lockerbox/Locker/node_modules/oauth/lib/oauth.js:510:17\n    at passBackControl (/Users/steven/lockerbox/Locker/node_modules/oauth/lib/oauth.js:366:13)\n    at IncomingMessage.<anonymous> (/Users/steven/lockerbox/Locker/node_modules/oauth/lib/oauth.js:378:9)\n    at IncomingMessage.emit (events.js:81:20)\n    at HTTPParser.onMessageComplete (http.js:133:23)\n    at CleartextStream.ondata (http.js:1231:22)\n    at CleartextStream._push (tls.js:303:27)\n    at SecurePair.cycle (tls.js:577:20)'

**Comment by quartzjer** [comment] 2011-12-21 15:59
This error is a failed authentication from twitter, ping me direct via IRC and I'll help you take a look at your oauth keys, it's probably a callback url mismatch (oauth makes it difficult or impossible to debug what went wrong sometimes).

**Comment by quartzjer** [comment] 2011-12-21 16:02
Moving this to #511

**Closed as completed by quartzjer** 2011-12-21 16:02 UTC
