### ISSUE TITLE
Socket hang up (links/facebook?)

### ISSUE THREAD

**Issue by nym** [LockerProject/Locker#205] opened 2011-09-08 02:18 UTC
7 Sep 19:16:35 - debug: Firing an event for home/facebook from synclet/facebook action(new)
7 Sep 19:16:35 - debug: Firing event to links to /events
7 Sep 19:16:35 - debug: Firing an event for home/facebook from synclet/facebook action(new)
7 Sep 19:16:35 - debug: Firing event to links to /events

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
Error: socket hang up
    at Socket.<anonymous> (http.js:1287:45)
    at Socket.emit (events.js:64:17)
    at Array.<anonymous> (net.js:831:12)
    at EventEmitter._tickCallback (node.js:126:26)

**Comment by ctide** [comment] 2011-09-13 21:05
Dupe of #202

**Closed as completed by ctide** 2011-09-13 21:05 UTC
