### ISSUE TITLE
node >= 0.5.4 compat

### ISSUE THREAD

**Issue by indexzero** [LockerProject/Locker#489] opened 2011-12-06 21:36 UTC
- `require.paths` does not exist.
- `sys` is now `util`

**Comment by quartzjer** [comment] 2011-12-06 21:51
We're actually blocking on https://github.com/nodejitsu/node-http-proxy/issues/159 to get to 0.6, have a nodev0.6 branch w/ all that cleaned up and just waiting :)

**Comment by indexzero** [comment] 2011-12-06 21:56
Haha. Ok. I get the hint :-)

**Comment by othiym23** [comment] 2011-12-12 21:48
Jer, you're the best person to keep an eye on this, as you're closest to http-proxy right now. This is a priority inasmuch as we know we want to move to 0.6 ASAP.

**Comment by quartzjer** [comment] 2011-12-12 22:02
Yep, last status update is that it's landing next week, excited to move to 0.6!

**Comment by merc3po** [comment] 2012-01-31 00:54
Is this fixed now?

**Comment by quartzjer** [comment] 2012-01-31 01:04
Nope but it's a duplicate of #533 pull req now so I'm closing this one :)

**Closed as completed by quartzjer** 2012-01-31 01:04 UTC
Labels: OPT-CLOSE

**Comment by indexzero** [comment] 2012-01-31 01:21
@quartzjer Sure you're aware, but `node-http-proxy@0.8.x` is compatibile with `node >= 0.5.6`. We've been running it in prod at nodejitsu for about a month now (since 0.6.6)

**Comment by quartzjer** [comment] 2012-01-31 01:25
Yep!  We've got it running here too in a branch, we just don't have
all the other modules changes integrated and tested yet (working
through a backlog), should be in sync this week, thanks!

On Mon, Jan 30, 2012 at 7:21 PM, Charlie Robbins
reply@reply.github.com
wrote:
