### ISSUE TITLE
When links processes a url and it fails, should re-try

### ISSUE THREAD

**Issue by quartzjer** [LockerProject/Locker#415] opened 2011-11-11 01:53 UTC
Sometimes the link expansion fails/errors (more often w/ t.co), and that condition should be captured and re-tried later again one or more times.

**Comment by smurthas** [comment] 2011-11-29 21:12
+1

**Comment by smurthas** [comment] 2011-11-29 21:17
Actually, dupe of https://github.com/LockerProject/Locker/issues/369

Closing this one.

**Closed as completed by smurthas** 2011-11-29 21:17 UTC
