### ISSUE TITLE
Racy tests

### ISSUE THREAD

**Issue by smurthas** [LockerProject/Locker#318] opened 2011-10-13 16:59 UTC
I haven't investigated, but the following tests broke on my last run. Rerunning "solved" it. Feels like a race condition:

```
  Installed services can be executed immediately rather than waiting for next run and after running generates data in mongo
    ✓ successfully
{ name: 'testSynclet',
  frequency: 1200,
  run: 'testSynclet.js',
  status: 'running',
  nextRun: Thu, 13 Oct 2011 16:56:35 GMT,
  workingDirectory: '/Users/Simon/dev/Locker/tests/Data/testSynclet' }
  Installed services can be executed immediately rather than waiting for next run
    ✗ successfully
      » expected null, got 'already running' // lsyncmanager-test-local.js:178
    ✗ and services specifying a positive nextRun time in the past get rescheduled at the next interval time
      » expected expression to evaluate to true, but was false // lsyncmanager-test-local.js:183
```

```
  Running testSynclet again
    ✗ with no data will leave everything intact
      » An unexpected error was caught: "already running"
  If the source doesn't return an ID
    ✗ it will generate a delete event and remove the row from mongo
      » expected 1,
    got  0 (==) // lsyncmanager-test-local.js:291
  Running testSynclet again
    ✗ with no value for 'notId'
      » expected 'no value for primary key',
    got  undefined (==) // lsyncmanager-test-local.js:302
```

**Comment by ctide** [comment] 2011-10-13 17:51
Dupe of #291

**Closed as completed by ctide** 2011-10-13 17:51 UTC
