### ISSUE TITLE
Flickr photos aren't completely syncing with my locker

### ISSUE THREAD

**Issue by amcjen** [LockerProject/Locker#212] opened 2011-09-16 02:00 UTC
When attempting to load in all my photos from my Flickr pro account, I only get several dozen, and I have 1500 photos on Flickr.

**Comment by smurthas** [comment] 2011-09-16 04:14
Could you start from a clean Me dir, add only Flickr, and paste the whole log file?

**Comment by bassdread** [comment] 2011-09-16 12:09
I am having the same issue, here is my log: https://gist.github.com/1221960

I removed my Me dir but on starting Locker up I had to create an account on the setup page to get to the main dashboard. I created a github one as it has no images.

In the log I stopped and started Locker hoping for it to start collecting photos. Looking at my Me directory there are no images. There is an auth.json in Me/flickr with what appears to be a valid token.

This was from the latest Master branch as of time of this comment. Let me know if you need anything else.

**Comment by bassdread** [comment] 2011-09-16 12:31
From adding some debug it looks to me that it never fetches anything from flickr.

**Comment by smurthas** [comment] 2011-09-16 15:02
bassdread - it looks like you re using the old Flickr Connector. We've moved the code over to the Flickr synclet, which can be set up through the UseUI.

Eric, you are using the synclet - correct?

**Comment by amcjen** [comment] 2011-09-16 16:03
Hrmm, I shut down my locker, moved out my Me/ directory, restarted the locker, and everything still loads in my contacts directory.  I also see this in my services tab:  http://cl.ly/1G082d3F013s3e2f1C3d

**Comment by bassdread** [comment] 2011-09-18 19:35
@smurthas will do, cheers.

**Comment by bassdread** [comment] 2011-09-18 19:56
So using the new flickr synclet I get the following error: https://gist.github.com/1225482 Seems there is an issue processing my flickr data, not sure if its the contacts or photos.

I am not sure if this error is related to Eric's issue.

**Comment by smurthas** [comment] 2011-09-30 16:28
eric, are you able to reproduce any of this? If not, I'm going to close the issue.

**Comment by othiym23** [comment] 2011-09-30 18:55
Don't forget that a lot of the Flickr data is cached in Mongo, so if you did have the old Flickr connector installed, you have to remove it and drop the old Flickr collections from Mongo. You'll have to reconnect to Flickr when you start your locker again, but all your data should get pulled down properly after that.

Simon, we should leave this issue as a placeholder until we decide whether we want to come up with some way of warning / migrating users who have installed the old connector that having it around causes problems.

**Comment by smurthas** [comment] 2011-10-04 07:01
Leaving this as a place holder per othiym23's comment, but removing it form the current milestone.

**Comment by smurthas** [comment] 2011-10-14 23:55
this is resolved, per conversation with @jeremie

**Closed as completed by smurthas** 2011-10-14 23:55 UTC
